export const THERMOMETER_MEAN_MAXIMUM_DEVIATION = 0.5
export const THERMOMETER_ULTRA_PRECISE_STANDARD_DEVIATION_NORM = 3
export const THERMOMETER_VERY_PRECISE_STANDARD_DEVIATION_NORM = 5
export const HUMIDITY_KEEP_DEVIATION_NORM = 1
export const MONOXIDE_KEEP_DEVIATION_NORM = 3
